# -*- coding: utf-8 -*-
"""YouTube-Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYA0GeJHWPNs6405N8QBlz_tRkodPSqh
"""

# ================================
# Preprocessing Pipeline
# ================================

# Import libraries
import pandas as pd
import re
from langdetect import detect
from tqdm import tqdm

# Enable progress bar
tqdm.pandas()

# ================================
# Load Data
# ================================
comments_df = pd.read_csv("comments.csv")

# ================================
# Basic Cleaning
# ================================
comments_df = comments_df.dropna(subset=["comment_text"])
comments_df["comment_text"] = comments_df["comment_text"].astype(str)

# ================================
# Text Cleaning Function
# ================================
def clean_text(text):
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

# Apply cleaning
comments_df["clean_text"] = comments_df["comment_text"].apply(clean_text)

# ================================
# Remove Duplicates
# ================================
comments_df = comments_df.drop_duplicates(subset=["clean_text"])

# ================================
# Remove Very Short Comments
# ================================
comments_df["text_length"] = comments_df["clean_text"].str.len()
comments_df = comments_df[comments_df["text_length"] >= 5]

# ================================
# Language Detection
# ================================
def detect_language(text):
    try:
        return detect(text)
    except:
        return "unknown"

comments_df["language"] = comments_df["clean_text"].progress_apply(detect_language)

# Keep only English comments
comments_df = comments_df[comments_df["language"] == "en"]

# ================================
# Spam/Bot Filtering
# ================================
spam_patterns = [
    "subscribe",
    "check my channel",
    "free followers",
    "giveaway",
    "click here",
    "promo"
]

def is_spam(text):
    return any(pattern in text for pattern in spam_patterns)

comments_df["is_spam"] = comments_df["clean_text"].apply(is_spam)
comments_df = comments_df[comments_df["is_spam"] == False]

# ================================
# Final Cleanup
# ================================
comments_df = comments_df.drop(columns=["text_length", "is_spam"])
comments_df = comments_df.reset_index(drop=True)

# ================================
# Save Cleaned Data
# ================================
comments_df.to_csv("comments_cleaned.csv", index=False)

print("✅ Cleaned comments saved as comments_cleaned.csv")

# ================================
# Engagement Analysis Pipeline
# ================================

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt

# ================================
# Load Data
# ================================
videos = pd.read_csv("videos.csv")

# ================================
# Data Cleaning
# ================================
engagement_cols = ["views", "likes", "comments"]

# Convert columns to numeric
for col in engagement_cols:
    videos[col] = pd.to_numeric(videos[col], errors="coerce")

# Remove rows with missing engagement values
videos = videos.dropna(subset=engagement_cols)

# ================================
# Aggregation
# ================================
engagement_summary = (
    videos
    .groupby("influencer")[engagement_cols]
    .sum()
    .reset_index()
)

print("=== Engagement Summary per Influencer ===")
print(engagement_summary)

# ================================
# Basic Statistics
# ================================
print("\n=== Dataset Overview ===")
print("Number of videos:", len(videos))
print("Number of comments:", len(comments))
print("Number of influencers:", videos["influencer"].nunique())

# ================================
# Distribution Analysis
# ================================
print("\n=== Videos per Influencer ===")
print(videos["influencer"].value_counts())

print("\n=== Comments per Influencer ===")
print(comments["influencer"].value_counts())

# ================================
# Influencer Analysis Pipeline
# ================================

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

# ================================
# Load Data
# ================================
videos = pd.read_csv("videos.csv")          # columns: influencer, views, likes, comments
comments = pd.read_csv("comments.csv")      # columns: influencer, clean_text

# ================================
# Emoji Counting Function
# ================================
def count_emojis(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map
        u"\U0001F1E0-\U0001F1FF"  # flags
        u"\u2600-\u26FF\u2700-\u27BF"
        "]+",
        flags=re.UNICODE
    )
    return len(emoji_pattern.findall(str(text)))

# Apply emoji count
comments["emoji_count"] = comments["clean_text"].apply(count_emojis)

# ================================
# Influencer-Level Aggregation
# ================================

# Video-based metrics
influencer_summary = (
    videos
    .groupby("influencer")
    .agg(
        total_views=("views", "sum"),
        avg_views=("views", "mean"),
        total_likes=("likes", "sum"),
        avg_likes=("likes", "mean"),
        total_comments=("comments", "sum")
    )
    .reset_index()
)

# Comment count per influencer
num_comments = (
    comments
    .groupby("influencer")
    .size()
    .reset_index(name="num_comments")
)

# Emoji usage per influencer
emoji_summary = (
    comments
    .groupby("influencer")["emoji_count"]
    .sum()
    .reset_index()
)

# Merge all summaries
influencer_summary = influencer_summary.merge(num_comments, on="influencer")
influencer_summary = influencer_summary.merge(emoji_summary, on="influencer")

print("=== Influencer Summary ===")
print(influencer_summary)

# ================================
# Visualization Function
# ================================
def hbar_plot(df, x_col, y_col, title, xlabel):
    plt.figure(figsize=(10, 6))
    sns.barplot(data=df, y=y_col, x=x_col, orient="h")

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Influencer")

    # Add value labels
    for i, v in enumerate(df[x_col]):
        plt.text(v + max(df[x_col]) * 0.01, i, f"{v:,.0f}", va="center")

    plt.tight_layout()
    plt.show()

# ================================
# Plots
# ================================

hbar_plot(influencer_summary, "total_views", "influencer",
          "Total Views per Influencer", "Views")

hbar_plot(influencer_summary, "avg_views", "influencer",
          "Average Views per Video", "Views")

hbar_plot(influencer_summary, "total_likes", "influencer",
          "Total Likes per Influencer", "Likes")

hbar_plot(influencer_summary, "avg_likes", "influencer",
          "Average Likes per Video", "Likes")

hbar_plot(influencer_summary, "num_comments", "influencer",
          "Total Comments per Influencer", "Number of Comments")

hbar_plot(influencer_summary, "emoji_count", "influencer",
          "Total Emoji Usage per Influencer", "Number of Emojis")

# ================================
# Comment Length Analysis
# ================================
comments["comment_length"] = comments["clean_text"].apply(lambda x: len(str(x)))

comment_length_summary = (
    comments
    .groupby("influencer")["comment_length"]
    .agg(["mean", "median", "max", "min"])
    .reset_index()
)

print("\n=== Comment Length Summary ===")
print(comment_length_summary)

# Plot average comment length
hbar_plot(comment_length_summary, "mean", "influencer",
          "Average Comment Length per Influencer", "Characters")

# ================================
# Survey Analysis Pipeline
# ================================

# --- Import libraries ---
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy.stats import ttest_ind

# ================================
# Load Data
# ================================
df = pd.read_csv("survey.csv")
print("Columns in dataset:", df.columns)

# ================================
# 1. Demographics Visualization
# ================================

# Age group
age_counts = df["Q16. Age group"].value_counts().sort_index()
age_counts.plot(kind="bar")
plt.title("Age Group Distribution")
plt.xlabel("Age Group")
plt.ylabel("Number of Respondents")
plt.tight_layout()
plt.show()

# Gender
gender_counts = df["Q17. Gender"].value_counts()
gender_counts.plot(kind="bar")
plt.title("Gender Distribution of Respondents")
plt.xlabel("Gender")
plt.ylabel("Number of Respondents")
plt.tight_layout()
plt.show()

# Platform usage
platform_counts = df["Q2. Which platform do you most frequently use to follow influencers?"].value_counts()
platform_counts.plot(kind="bar")
plt.title("Primary Platform Used to Follow Influencers")
plt.xlabel("Platform")
plt.ylabel("Number of Respondents")
plt.tight_layout()
plt.show()

# Purchase influence
purchase_counts = df["Q15. Have influencers influenced your purchasing or adoption decisions?"].value_counts()
purchase_counts.plot(kind="bar")
plt.title("Influencer Impact on Purchase Decisions")
plt.xlabel("Response")
plt.ylabel("Number of Respondents")
plt.tight_layout()
plt.show()

# ================================
# 2. Likert-scale Processing
# ================================
likert_cols = ["Q5. I consider the influencers I follow to be trustworthy.",
               "Q6. Influencers I follow seem authentic rather than scripted.",
               "Q7. I feel a sense of personal connection with influencers I follow.",
               "Q8. I trust influencers' opinions on lifestyle-related topics.",
               "Q9. Influencer content often affects my mood or emotions.",
               "Q10. I feel emotionally motivated by influencer content.",
               "Q11. I relate emotionally to the lifestyles presented by influencers.",
               "Q12. Influencer content has influenced my lifestyle habits (e.g., routines, self-care, fitness).",
               "Q13. I have tried products, services, or routines recommended by influencers.",
               "Q14. Influencer content influences my perception of an “ideal” lifestyle."]

df[likert_cols] = df[likert_cols].apply(pd.to_numeric, errors="coerce")

# ================================
# 3. Construct-Level Aggregation
# ================================
constructs = {
    "Credibility & Trust": ["Q5", "Q6", "Q7", "Q8"],
    "Emotional Impact": ["Q9", "Q10", "Q11"],
    "Lifestyle & Purchase Influence": ["Q12", "Q13", "Q14"]
}

# Summary table
summary = []
for name, questions in constructs.items():
    summary.append({
        "Construct": name,
        "Mean Score": df[questions].mean().mean()
    })
construct_table = pd.DataFrame(summary)
print("=== Construct Mean Scores ===")
print(construct_table)

# ================================
# 4. Correlation Analysis
# ================================
# Compute construct scores per respondent
df["Credibility & Trust"] = df[constructs["Credibility & Trust"]].mean(axis=1)
df["Emotional Impact"] = df[constructs["Emotional Impact"]].mean(axis=1)
df["Lifestyle & Purchase Influence"] = df[constructs["Lifestyle & Purchase Influence"]].mean(axis=1)

# Correlation matrix
construct_cols_for_corr = ["Credibility & Trust", "Emotional Impact", "Lifestyle & Purchase Influence"]
cor_matrix = df[construct_cols_for_corr].corr()
print("\n=== Correlation Matrix ===")
print(cor_matrix)

# Heatmap
sns.heatmap(cor_matrix, annot=True, cmap="coolwarm", vmin=-1, vmax=1)
plt.title("Correlation Matrix of Survey Constructs")
plt.show()

# ================================
# 5. Regression Analysis
# ================================
X = df[["Credibility & Trust", "Emotional Impact"]]  # predictors
y = df["Lifestyle & Purchase Influence"]             # dependent variable
X = sm.add_constant(X)  # add intercept
model = sm.OLS(y, X).fit()
print("\n=== Regression Model Summary ===")
print(model.summary())

# ================================
# 6. Group Comparison by Trust
# ================================
median_trust = df["Credibility & Trust"].median()
df["Trust Group"] = df["Credibility & Trust"].apply(lambda x: "High Trust" if x >= median_trust else "Low Trust")

# Mean per group
group_means = df.groupby("Trust Group")[["Emotional Impact", "Lifestyle & Purchase Influence"]].mean()
print("\n=== Mean Scores by Trust Group ===")
print(group_means)

# T-tests
high = df[df["Trust Group"]=="High Trust"]
low = df[df["Trust Group"]=="Low Trust"]

ttest_emotion = ttest_ind(high["Emotional Impact"], low["Emotional Impact"])
ttest_lifestyle = ttest_ind(high["Lifestyle & Purchase Influence"], low["Lifestyle & Purchase Influence"])

print("\n=== T-test Results ===")
print("Emotional Impact T-test:", ttest_emotion)
print("Lifestyle & Purchase Influence T-test:", ttest_lifestyle)

# Bar plot of group means
group_means.plot(kind="bar", figsize=(8,5))
plt.title("Mean Scores by Trust Group")
plt.ylabel("Mean Score (1-5)")
plt.xticks(rotation=0)
plt.ylim(1,5)
plt.legend(title="Construct")
plt.tight_layout()
plt.show()

# Save figure
plt.savefig("group_comparison_bar.png", dpi=300, bbox_inches="tight")
print("✅ Figure saved as group_comparison_bar.png")

